### ISSUE TITLE
Опечатка в слове

### ISSUE THREAD

**Issue by MashaOrlova** [MaksHladki/DDWA#1]
![1](https://cloud.githubusercontent.com/assets/22172490/22455484/dbeebefe-e79d-11e6-876d-5c304a7b92ed.png)

Опечатка в слове Пакетные

**Comment by MaksHladki** [comment]
![image](https://cloud.githubusercontent.com/assets/6429277/22459875/637f8870-e7b3-11e6-936a-b2559e86e851.png)
Исправлено, спасибо!
