### ISSUE TITLE
Тема 3, слайд 22

### ISSUE THREAD

**Issue by katyaRak** [MaksHladki/DDWA#75]
программами и приложениями Dropbox и серверами - это однородные члены, нужна либо запятая перед вторым "и", либо  написать "благозвучнее"
"Чтобы защитить информацию во время пересылки между программами, приложениями Dropbox и серверами....
![default](https://cloud.githubusercontent.com/assets/22168230/23104576/8ec5b936-f6e1-11e6-9261-008e1aa5c3a6.png)
"

**Comment by MaksHladki** [comment]
неправильный репозиторий, баг для CT
